name: Mclogs
version: 2.1.2
description: Easily share and analyse your server logs
author: Aternos Gmbh
website: https://mclo.gs

main: gs.mclo.bukkit.MclogsBukkitLoader
api-version: 1.13

commands:
  mclogs:
    description: Upload your logs to https://mclo.gs
    usage: "/mclogs <list|share> <filename>"
    permission: mclogs
