name: Mclogs
version: 2.1.1
description: Easily share and analyse your server logs
author: Aternos Gmbh
website: https://mclo.gs

main: gs.mclo.bukkit.MclogsBukkitLoader
api-version: 1.13

commands:
  mclogs:
    description: Share your logs to the mclogs API
    usage: "/mclogs <list|share> <filename>"
    permission: mclogs
