name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew shadowJar -Prelease=${{  github.ref_name }} --no-daemon
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/libs/mclogs-bukkit-${{  github.ref_name }}.jar
          body_path: ${{ github.workspace }}/CHANGELOG.md
          name: v${{ github.ref_name }}
      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth -Prelease=${{  github.ref_name }}