name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: init submodule
        run: git submodule init && git submodule update
      - name: Build with Gradle
        run: ./gradlew shadowJar -Prelease=${{  github.event.release.tag_name }}
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{  github.event.release.upload_url }}
          asset_path: ./build/libs/mclogs-bukkit-${{  github.event.release.tag_name }}.jar
          asset_name: mclogs-bukkit-${{  github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth -Prelease=${{  github.event.release.tag_name }} -Pchangelog="${{  github.event.release.body }}"